application: papertlogo
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /help.txt
  static_files: static/help.txt
  upload: static/help.txt

- url: /.*
  script: index.py
